[build-system]
requires = ["setuptools", "setuptools-scm"]
#build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["pyblend"]


[project]
name = "pyblend"
authors = [
    {name = "Hannes"},
    {name = "Olaf"},
    {name = "Daniel"},
]
description = "a package manager to install packages in your app"
readme = "README.md"
requires-python = ">=3.4"
keywords = ["blender"]
#license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.7",
]
#dynamic = ["dependencies"]
dependencies = ['importlib-metadata; python_version<"3.7"']
#dynamic = ["version"]
version = "0.0.1"

#[project.optional-dependencies]
#yaml = ["pyyaml"]

#[project.scripts]
#my-script = "my_package.module:function"

[project.urls]
# Homepage = "https://github.com/.."
# Source = "https://github.com/.."
